import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ur" | "hi";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.courses": "Courses",
    "nav.faculty": "Faculty",
    "nav.donation": "Donation",
    "nav.contact": "Contact",
    // Hero
    "hero.welcome": "Welcome to Darul Uloom Junaidia Ajmalia",
    "hero.subtitle": "Providing Quality Islamic & Modern Education since 2004 — Mahend, Ghazipur, Uttar Pradesh",
    "hero.slide1.badge": "Est. 2004",
    "hero.slide2.badge": "20+ Years",
    "hero.slide3.badge": "500+ Students",
    "hero.slide1.desc": "Join thousands of students who have built their foundation in Quran, Hadith, and modern sciences. Admissions open for the new academic year.",
    "hero.slide2.desc": "From Hifz-ul-Quran to modern academics — our structured programs are designed to nurture every student's potential and prepare them for life.",
    "hero.slide3.desc": "Your generous support keeps the doors of knowledge open. Help us continue providing free and subsidized education to deserving students.",
    "hero.apply": "Apply Now",
    "hero.donate": "Donate Now",
    // About Preview
    "about.preview.title": "About Our Madarsa",
    "about.preview.text": "We are more than an educational institution-we are a foundation for building character, purpose, and future leadership. Established by Hazrat Syed Akmal Ahmad Ajmali (Rahmatullah Alaih), our Madarsa was founded with a clear vision: to create a learning environment where Islamic values and modern knowledge coexist in harmony. We believe that true education is not limited to books-it shapes mindset, discipline, and responsibility. Our approach combines Quranic teachings, academic learning, and personal development to nurture individuals who are confident, ethically grounded, and prepared to face real-world challenges. Every student here is guided not only to gain knowledge, but to live with integrity, purpose, and a sense of contribution to society. With a focus on excellence, discipline, and continuous growth, we are committed to shaping a generation that leads with knowledge, lives with values, and inspires positive change.",
    "about.preview.readmore": "Read More",
    // Courses
    "courses.title": "Our Courses",
    "courses.subtitle": "Comprehensive Islamic & Modern Education Programs",
    "course.hifz.name": "Hifz-ul-Quran",
    "course.hifz.desc": "Complete memorization of the Holy Quran with proper Tajweed rules and pronunciation.",
    "course.hifz.duration": "Duration: 2-3 Years",
    "course.nazra.name": "Nazra Quran",
    "course.nazra.desc": "Learning to read the Holy Quran fluently with correct pronunciation and basic Tajweed.",
    "course.nazra.duration": "Duration: 6-12 Months",
    "course.alim.name": "Class 1 to 8 (Urdu & Hindi Medium)",
    "course.alim.desc": "Science, Math, English, Hindi, Urdu, Deeniyat, and Quran Education are taught in Urdu and Hindi medium following the school curriculum.",
    "course.alim.duration": "Duration: 8 Years",
    // Course duration units
    "course.unit.days": "Days",
    "course.unit.weeks": "Weeks",
    "course.unit.months": "Months",
    "course.unit.years": "Years",
    // Course level labels
    "course.level.beginners": "Beginners",
    "course.level.intermediate": "Intermediate",
    "course.level.advanced": "Advanced",
    "course.level.allages": "All Ages",
    // Faculty
    "faculty.title": "Our Faculty",
    "faculty.subtitle": "Experienced and Dedicated Teachers",
    "faculty.teacher1.name": "Hafiz MD Tanwir Zaki",
    "faculty.teacher1.title": "Principal",
    "faculty.teacher1.qual": "Quran & Deeniyat",
    "faculty.teacher2.name": "Hafiz Qari Sabir Hussain",
    "faculty.teacher2.title": "Teacher",
    "faculty.teacher2.qual": "Subjects: Urdu, Qira'at",
    "faculty.teacher3.name": "Hafiz Qari Imran Khan",
    "faculty.teacher3.title": "Teacher",
    "faculty.teacher3.qual": "Subjects: Urdu, Qira'at ",
    // Donation
    "donation.title": "Support Islamic Education",
    "donation.subtitle": "Support Islamic Education for a Better Future",
    "donation.text": "Your generous contribution helps us provide quality Islamic and modern education to students who need it most. Every donation makes a difference.",
    "donation.button": "Donate Now",
    "donation.upi": "UPI ID",
    "donation.bank": "Bank Details",
    "donation.bank.name": "Bank Name: State Bank",
    "donation.bank.account": "Account: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "Your contribution helps us educate future generations.",
    // Footer
    "footer.contact": "Contact Us",
    "footer.phone": "Phone: +91 9876543210",
    "footer.email": "Email: darululoomjunaidiaajmalia@gmail.com",
    "footer.address": "Mahend, Ghazipur, Uttar Pradesh",
    "footer.quicklinks": "Quick Links",
    "footer.copyright": "© 2026 Darul Uloom Junaidia Ajmalia. All rights reserved.",
    "footer.followus": "Follow Us",
    "footer.desc": "Learning, growth, and responsibility. Empowering individuals with values and skills. Together for a better society.",
    // About Page
    "about.title": "About Darul Uloom Junaidia Ajmalia",
    "about.history.title": "Our History",
    "about.history.text": "The Madarsa was established by Hazrat Syed Akmal Ahmad Ajmali (Rahmatullah Alaih) with the vision of providing a balanced education that combines Islamic teachings with modern knowledge and overall personality development. It began as a small learning center focused on Quranic studies along with basic academic learning. With continuous dedication and strong community support, the Madarsa gradually expanded its programs to include Hifz-ul-Quran, Nazra, and structured academic education. Today, it has developed into a respected institution known for its disciplined environment, qualified faculty, and commitment to nurturing students who are spiritually aware, intellectually capable, and socially responsible.",
    "about.mission.title": "Our Mission",
    "about.mission.text": "Our mission is to provide quality Islamic and modern education that nurtures spiritual growth, moral values, and intellectual development. We aim to empower students with knowledge of the Quran and Sunnah while preparing them to become responsible, ethical, and productive members of society.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "Our vision is to establish a distinguished Islamic educational institution recognized for excellence in knowledge, character, and service. We aspire to cultivate a generation that not only upholds Islamic values but also demonstrates leadership, responsibility, and positive contribution in an ever-evolving global society.",
    "about.founder.title": "Founder's Message",
    "about.founder.text": "\"Education is the light that dispels the darkness of ignorance. At Darul Uloom Junaidia Ajmalia, we strive to nurture not just the mind, but the soul and character of every student.\" — Hazrat Syed Akmal Ahmad Ajmali Rahmatullah Alaih (Sajjada Nashin)",
    "about.achievements.title": "Our Achievements",
    "about.achievements.students": "500+ Students Educated",
    "about.achievements.graduates": "200+ Hafiz Graduated",
    "about.achievements.years": "20+ Years of Service",
    "about.achievements.scholars": "14 Rooms & 3 Halls",
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "We'd love to hear from you",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.enquiry": "Select Inquiry Type",
    "contact.form.message": "Your Message",
    "contact.form.submit": "Send Message",
    "contact.info.title": "Contact Information",
    // Hero descriptions
    "hero.about.desc": "Established on 1 March 2004, we have been nurturing young minds with Islamic values and modern knowledge in the heart of Ghazipur, Uttar Pradesh.",
    "hero.courses.desc": "From Hifz-ul-Quran to Class 1–8 Hindi medium education — we offer a complete learning journey combining Islamic and modern subjects.",
    "hero.faculty.desc": "Our dedicated team of qualified teachers brings years of experience and a passion for shaping the next generation of scholars.",
    "hero.donation.desc": "Your generous support helps us provide free education, food, and shelter to students who need it most. Every contribution counts.",
    "hero.contact.desc": "Have a question or want to enroll? We are here to help. Reach out to us and we will get back to you as soon as possible.",
    // About page extra
    "about.ourstory": "Our Story",
    "about.milestones": "Milestones",
    "about.ourjourney": "Our Journey",
    "about.purpose": "Purpose",
    "about.missionvision": "Mission Statement",
    "about.whatdrivesus": "What Drives Us",
    "about.corevalues": "Core Values",
    "about.wordswisdom": "Words of Wisdom",
    "about.joincommunity": "Join Our Community",
    "about.jointext": "Become part of our educational journey. Apply today or support our mission through donation.",
    "about.sendmessage": "Send Message",
    // Timeline
    "timeline.2004": "Darul Uloom Junaidia Ajmalia was founded on 1 March 2004 by Hazrat Syed Akmal Ahmad Ajmali Rahmatullah Alaih (Sajjada Nashin).",
    "timeline.2006": "The first student batch completed foundational studies as admissions steadily increased with community support.",
    "timeline.2010": "Campus expansion added 14 rooms, 3 big halls, an office, and a library to support growing academic needs.",
    "timeline.2015": "The curriculum expanded from Class 1 to 8, including Science, Math, English, Hindi, Urdu, Deeniyat, and Quran Education.",
    "timeline.2024": "The institution crossed 500+ students with a dedicated team of 7 teachers.",
    // Values
    "value.knowledge.title": "Authentic Knowledge",
    "value.knowledge.desc": "Every lesson is rooted in reliable Islamic knowledge from the Quran and Sunnah.",
    "value.teaching.title": "Compassionate Teaching",
    "value.teaching.desc": "Our teachers mentor each student with patience, care, and personal attention.",
    "value.service.title": "Service to Community",
    "value.service.desc": "We support the local community through outreach, events, and accessible education.",
    "value.excellence.title": "Excellence",
    "value.excellence.desc": "We uphold high standards in both Islamic studies and modern education.",
    // Faculty page
    "faculty.ourteam": "Our Team",
    "faculty.experienced": "Dedicated & Experienced",
    "faculty.manager.title": "Managing Director",
    "faculty.manager.qual": "Office Management",
    "faculty.principal.title": "Principal",
    "faculty.principal.qual": "Quran & Deeniyat",
    "faculty.teacher.title": "Teacher",
    "faculty.member.manager": "Syed Jagan Hasan Ajmali",
    "faculty.member.tabrez": "Hafiz MD Tanwir Zaki",
    "faculty.member.jabir": "Hafiz Qari Sabir Hussain",
    "faculty.member.usman": "Hafiz Qari Imran Khan",
    "faculty.member.abdullah": "Hafiz Abdullah Khan",
    "faculty.member.nizam": "Master Md. Nizamuddin",
    "faculty.member.jamshed": "Master Jamshed Khan",
    "faculty.member.pawan": "Master Parvej Ahmad",
    "faculty.jabir.qual": "Subjects: Urdu, Qira'at",
    "faculty.usman.qual": "Subjects: Urdu, Qira'at ",
    "faculty.abdullah.qual": "Subjects: Arabic",
    "faculty.nizamuddin.qual": "Subjects: Hindi, Math",
    "faculty.jamshed.qual": "Subjects: Math, General Knowledge",
    "faculty.pawan.qual": "Subjects: English, Social Science",
    "home.leadership.badge": "Leadership Team",
    "home.leadership.heading": "Management & Leadership",
    "home.leadership.subheading": "Manager and Principal",
    "home.leadership.viewFaculty": "View Full Faculty",
    // Home page labels/news
    "home.news.pinned": "Pinned",
    "home.news.event": "Event",
    "home.news.notice": "Notice",
    "home.news.heading": "Announcements & News",
    "home.news.subheading": "Stay updated with the latest from Darul Uloom Junaidia Ajmalia",
    "home.news.admission.title": "New Admissions Open for 2026-27 Academic Year",
    "home.news.admission.desc": "Darul Uloom Junaidia Ajmalia is now accepting applications for Hifz, Nazra and Class 1-8. Limited seats, apply early.",
    "home.news.quran.title": "Annual Quran Recitation Competition",
    "home.news.quran.desc": "Join our yearly Quran recitation event open to all students and community members.",
    "home.news.eid.title": "Eid Holiday Schedule",
    "home.news.eid.desc": "Madarsa closed April 18-22 for Eid. Classes resume April 23.",
    "home.news.readmore": "Read more",
    "home.news.viewall": "View All Announcements",
    // Courses page
    "courses.readytojoin": "Ready to Begin Your Journey?",
    "courses.enrolltext": "Enroll today and take the first step towards comprehensive Islamic education.",
    // Contact & Donation
    "contact.sendmessage": "Send a Message",
    "contact.getintouch": "Get In Touch",
    "contact.location": "Mehdur, Ghazipur",
    "contact.locationdesc": "Uttar Pradesh",
    "donation.supportus": "Support Us",
    "donation.howtodonate": "How to Donate",
    "donation.jazakallah": "JazakAllah Khair - your generous contribution helps us provide quality education to students who need it most.",
    "donation.scantext": "Scan or copy UPI ID to donate instantly",
    "donation.form.name": "Name *",
    "donation.form.phone": "Phone Number *",
    "donation.form.email": "Email ID (optional)",
    "donation.form.address": "Address (optional)",
    "donation.form.whydonate.label": "Why Donate (Trust + Clarity)",
    "donation.form.whydonate.placeholder": "Click to see why you should donate",
    "donation.form.type.label": "Donation Type",
    "donation.form.type.placeholder": "Select donation type",
    "donation.form.submit": "Donate Now",
    "donation.form.other.placeholder": "Please describe your donation reason...",
    "donation.type.zakat": "Zakat",
    "donation.type.sadaqah": "Sadaqah",
    "donation.type.sponsorship": "Student Sponsorship",
    "donation.type.education": "Education Support",
    "donation.type.food": "Food Support",
    "donation.type.building": "Building Fund",
    "donation.type.general": "General Donation",
    "donation.type.other": "Other",
    "donation.why.1": "Free education for underprivileged students",
    "donation.why.2": "Quran memorization programs",
    "donation.why.3": "Food & accommodation support",
    "donation.why.4": "Books & study material",
    "donation.popup.title": "JazakAllah Khair!",
    "donation.popup.msg1": "Thank you for your interest in supporting Islamic education. WhatsApp has opened — please send the message to connect with us.",
    "donation.popup.msg2": "We will get back to you as soon as possible. Please be patient — May Allah reward you abundantly. 🤲",
    "donation.popup.btn": "Send on WhatsApp",
    "donation.popup.close": "Close this window",
    // About gallery
    "about.gallery.title": "Photo Gallery",
    "about.gallery.subtitle": "A glimpse into life at Darul Uloom Junaidia Ajmalia",
    // Footer
    "footer.contactmap": "Contact & Map",
    // Contact enquiry types
    "contact.enquiry.course": "Course Inquiry",
    "contact.enquiry.donation": "Donation",
    "contact.enquiry.other": "Other",
    // Donation CTA badge
    "donation.cta.badge": "Support",
  },

  // ─────────────────────────────────────────────
  // URDU
  // ─────────────────────────────────────────────
  ur: {
    // Nav
    "nav.home": "ہوم",
    "nav.about": "ہمارے بارے میں",
    "nav.courses": "کورسز",
    "nav.faculty": "اساتذہ",
    "nav.donation": "عطیات",
    "nav.contact": "رابطہ",
    // Hero
    "hero.welcome": "دارالعلوم جنیدیہ اجمالیہ میں خوش آمدید",
    "hero.subtitle": "2004 سے معیاری اسلامی اور جدید تعلیم — مہند، غازی پور، اتر پردیش",
    "hero.slide1.badge": "قیام 2004",
    "hero.slide2.badge": "20+ سال",
    "hero.slide3.badge": "500+ طلباء",
    "hero.slide1.desc": "ہزاروں طلباء کے ساتھ شامل ہوں جنہوں نے قرآن، حدیث اور جدید علوم میں اپنی بنیاد مضبوط کی۔ نئے تعلیمی سال کے لیے داخلے کھلے ہیں۔",
    "hero.slide2.desc": "حفظ القرآن سے جدید تعلیم تک — ہمارے منظم پروگرام ہر طالب علم کی صلاحیتوں کو نکھارنے کے لیے بنائے گئے ہیں۔",
    "hero.slide3.desc": "آپ کی سخاوت علم کے دروازے کھلے رکھتی ہے۔ مستحق طلباء کو مفت اور سبسڈی والی تعلیم فراہم کرنے میں ہماری مدد کریں۔",
    "hero.apply": "ابھی درخواست دیں",
    "hero.donate": "ابھی عطیہ دیں",
    // About Preview
    "about.preview.title": "ہمارے مدرسے کے بارے میں",
    "about.preview.text": "ہم صرف ایک تعلیمی ادارہ نہیں بلکہ کردار، مقصد اور مستقبل کی قیادت کی تعمیر کی بنیاد ہیں۔ حضرت سید اکمل احمد اجمالی (رحمۃ اللہ علیہ) نے ہمارے مدرسے کو اس واضح وژن کے ساتھ قائم کیا کہ ایسا تعلیمی ماحول بنایا جائے جہاں اسلامی اقدار اور جدید علم ہم آہنگی کے ساتھ ساتھ چلیں۔ ہمارا یقین ہے کہ حقیقی تعلیم صرف کتابوں تک محدود نہیں ہوتی، بلکہ سوچ، نظم و ضبط اور ذمہ داری کو تشکیل دیتی ہے۔ ہمارا طریقۂ تعلیم قرآنی تعلیمات، درسی تعلیم اور ذاتی نشوونما کو یکجا کرتا ہے تاکہ ایسے افراد تیار ہوں جو بااعتماد، اخلاقی طور پر مضبوط اور عملی زندگی کے چیلنجز کا سامنا کرنے کے لیے تیار ہوں۔ یہاں ہر طالب علم کو صرف علم حاصل کرنے ہی نہیں بلکہ دیانت، مقصد اور معاشرے میں مثبت کردار کے ساتھ زندگی گزارنے کی رہنمائی دی جاتی ہے۔",
    "about.preview.readmore": "مزید پڑھیں",
    // Courses
    "courses.title": "ہمارے کورسز",
    "courses.subtitle": "جامع اسلامی اور جدید تعلیمی پروگرامز",
    "course.hifz.name": "حفظ القرآن",
    "course.hifz.desc": "تجوید کے مکمل قواعد اور تلفظ کے ساتھ قرآن مجید کا مکمل حفظ۔",
    "course.hifz.duration": "مدت: 2-3 سال",
    "course.nazra.name": "ناظرہ قرآن",
    "course.nazra.desc": "صحیح تلفظ اور بنیادی تجوید کے ساتھ قرآن مجید روانی سے پڑھنا سیکھنا۔",
    "course.nazra.duration": "مدت: 6-12 ماہ",
    "course.alim.name": "جماعت 1 تا 8 (اردو اور ہندی میڈیم)",
    "course.alim.desc": "سائنس، ریاضی، انگریزی، ہندی، اردو، دینیات اور قرآنی تعلیم اردو اور ہندی میڈیم میں اسکول نصاب کے مطابق پڑھائی جاتی ہے۔",
    "course.alim.duration": "مدت: 8 سال",
    // Course duration units
    "course.unit.days": "دن",
    "course.unit.weeks": "ہفتے",
    "course.unit.months": "ماہ",
    "course.unit.years": "سال",
    // Course level labels
    "course.level.beginners": "ابتدائی",
    "course.level.intermediate": "درمیانی",
    "course.level.advanced": "اعلیٰ",
    "course.level.allages": "تمام عمر",
    // Faculty
    "faculty.title": "ہمارے اساتذہ",
    "faculty.subtitle": "تجربہ کار اور مخلص اساتذہ",
    "faculty.teacher1.name": "حافظ محمد تنویر ذکی",
    "faculty.teacher1.title": "پرنسپل",
    "faculty.teacher1.qual": "قرآن اور دینیات",
    "faculty.teacher2.name": "حافظ قاری صابر حسین",
    "faculty.teacher2.title": "استاد",
    "faculty.teacher2.qual": "مضامین: اردو، قراءت",
    "faculty.teacher3.name": "حافظ قاری عمران خان",
    "faculty.teacher3.title": "استاد",
    "faculty.teacher3.qual": "مضامین: اردو، قراءت",
    // Donation
    "donation.title": "اسلامی تعلیم کی حمایت کریں",
    "donation.subtitle": "بہتر مستقبل کے لیے اسلامی تعلیم کی حمایت کریں",
    "donation.text": "آپ کا سخاوتی عطیہ ان طلباء کو معیاری اسلامی اور جدید تعلیم فراہم کرنے میں مدد کرتا ہے جنہیں اس کی سب سے زیادہ ضرورت ہے۔ ہر عطیہ فرق ڈالتا ہے۔",
    "donation.button": "ابھی عطیہ دیں",
    "donation.upi": "یو پی آئی آئی ڈی",
    "donation.bank": "بینک تفصیلات",
    "donation.bank.name": "بینک کا نام: اسٹیٹ بینک",
    "donation.bank.account": "اکاؤنٹ: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "آپ کا تعاون آنے والی نسلوں کی تعلیم میں مدد کرتا ہے۔",
    // Footer
    "footer.contact": "ہم سے رابطہ کریں",
    "footer.phone": "فون: +91 9876543210",
    "footer.email": "ای میل: darululoomjunaidiaajmalia@gmail.com",
    "footer.address": "مہند، غازی پور، اتر پردیش",
    "footer.quicklinks": "فوری لنکس",
    "footer.copyright": "© 2026 دارالعلوم جنیدیہ اجمالیہ۔ جملہ حقوق محفوظ ہیں۔",
    "footer.followus": "ہمیں فالو کریں",
    "footer.desc": "سیکھنا، ترقی اور ذمہ داری۔ اقدار اور مہارتوں سے افراد کو بااختیار بنانا۔ ایک بہتر معاشرے کے لیے مل کر۔",
    // About Page
    "about.title": "دارالعلوم جنیدیہ اجمالیہ کے بارے میں",
    "about.history.title": "ہماری تاریخ",
    "about.history.text": "مدرسہ حضرت سید اکمل احمد اجمالی (رحمۃ اللہ علیہ) نے اس وژن کے ساتھ قائم کیا کہ ایسی متوازن تعلیم فراہم کی جائے جس میں اسلامی تعلیمات، جدید علم اور مجموعی شخصیت سازی شامل ہو۔ ابتدا میں یہ ایک چھوٹا تعلیمی مرکز تھا جہاں قرآنی تعلیم کے ساتھ بنیادی عصری مضامین پڑھائے جاتے تھے۔ مسلسل محنت اور مضبوط کمیونٹی تعاون کے نتیجے میں مدرسہ نے بتدریج اپنے پروگرامز میں حفظ القرآن، ناظرہ اور منظم درسی تعلیم شامل کی۔ آج یہ ایک باوقار ادارہ بن چکا ہے جو اپنے منضبط ماحول، اہل اساتذہ اور ذمہ دار شہریوں کی تیاری کے عزم کے لیے معروف ہے۔",
    "about.mission.title": "ہمارا مشن",
    "about.mission.text": "ہمارا مشن معیاری اسلامی اور جدید تعلیم فراہم کرنا ہے جو روحانی نشوونما، اخلاقی اقدار اور ذہنی ارتقا کو فروغ دے۔ ہم قرآن و سنت کے علم کے ذریعے طلبہ کو بااختیار بنانا چاہتے ہیں تاکہ وہ معاشرے کے ذمہ دار، بااخلاق اور کارآمد افراد بن سکیں۔",
    "about.vision.title": "ہمارا وژن",
    "about.vision.text": "ہمارا وژن ایک ممتاز اسلامی تعلیمی ادارہ قائم کرنا ہے جو علم، کردار اور خدمت میں امتیاز کے لیے پہچانا جائے۔ ہم ایسی نسل تیار کرنا چاہتے ہیں جو اسلامی اقدار پر قائم رہے اور بدلتی ہوئی عالمی دنیا میں قیادت، ذمہ داری اور مثبت کردار ادا کرے۔",
    "about.founder.title": "بانی کا پیغام",
    "about.founder.text": "\"تعلیم جہالت کی تاریکی کو دور کرنے والی روشنی ہے۔ دارالعلوم جنیدیہ اجمالیہ میں ہم ہر طالب علم کے ذہن کے ساتھ اس کے کردار اور روح کی بھی تربیت کرتے ہیں۔\" — حضرت سید اکمل احمد اجمالی رحمۃ اللہ علیہ (سجادہ نشین)",
    "about.achievements.title": "ہماری کامیابیاں",
    "about.achievements.students": "500+ طلباء کو تعلیم دی",
    "about.achievements.graduates": "200+ حافظ فارغ التحصیل",
    "about.achievements.years": "20+ سال خدمت",
    "about.achievements.scholars": "14 کمرے اور 3 بڑے ہال",
    // Contact Page
    "contact.title": "ہم سے رابطہ کریں",
    "contact.subtitle": "ہم آپ سے سننا چاہیں گے",
    "contact.form.name": "آپ کا نام",
    "contact.form.email": "آپ کا ای میل",
    "contact.form.enquiry": "استفسار کی قسم منتخب کریں",
    "contact.form.message": "آپ کا پیغام",
    "contact.form.submit": "پیغام بھیجیں",
    "contact.info.title": "رابطے کی معلومات",
    // Hero descriptions
    "hero.about.desc": "1 مارچ 2004 کو قائم، ہم غازی پور، اتر پردیش میں اسلامی اقدار اور جدید علم سے نوجوان ذہنوں کی تربیت کر رہے ہیں۔",
    "hero.courses.desc": "حفظ القرآن سے لے کر کلاس 1 تا 8 ہندی میڈیم تعلیم تک — ہم اسلامی اور جدید مضامین کو یکجا کرتے ہیں۔",
    "hero.faculty.desc": "ہمارے تجربہ کار اساتذہ کی ٹیم علم اور لگن کے ساتھ اگلی نسل کے علماء تیار کرنے میں مصروف ہے۔",
    "hero.donation.desc": "آپ کا سخاوتی تعاون ان طلباء کو مفت تعلیم، کھانا اور رہائش فراہم کرنے میں مدد کرتا ہے جنہیں اس کی سب سے زیادہ ضرورت ہے۔",
    "hero.contact.desc": "کوئی سوال ہے یا داخلہ لینا چاہتے ہیں؟ ہم یہاں مدد کے لیے موجود ہیں۔ ہم سے رابطہ کریں۔",
    // About page extra
    "about.ourstory": "ہماری کہانی",
    "about.milestones": "سنگ میل",
    "about.ourjourney": "ہمارا سفر",
    "about.purpose": "مقصد",
    "about.missionvision": "مشن اسٹیٹمنٹ",
    "about.whatdrivesus": "ہماری اقدار",
    "about.corevalues": "بنیادی اقدار",
    "about.wordswisdom": "حکمت کے الفاظ",
    "about.joincommunity": "ہماری برادری میں شامل ہوں",
    "about.jointext": "اسلامی تعلیم کی میراث کا حصہ بنیں۔ آج ہی درخواست دیں یا عطیہ دے کر ہمارے مشن کی حمایت کریں۔",
    "about.sendmessage": "پیغام بھیجیں",
    // Timeline
    "timeline.2004": "دارالعلوم جنیدیہ اجمالیہ کا قیام 1 مارچ 2004 کو حضرت سید اکمل احمد اجمالی رحمۃ اللہ علیہ (سجادہ نشین) نے کیا۔",
    "timeline.2006": "طلباء کا پہلا بیچ بنیادی تعلیم مکمل کر کے فارغ ہوا۔ کمیونٹی کی حمایت سے داخلے بڑھتے رہے۔",
    "timeline.2010": "نئی عمارت تعمیر ہوئی — 14 کمرے، 3 بڑے ہال، 1 دفتر اور 1 لائبریری کا اضافہ ہوا۔",
    "timeline.2015": "نصاب کو کلاس 1 تا 8 تک وسعت دی گئی جس میں سائنس، ریاضی، انگریزی، ہندی، اردو، دینیات اور قرآنی تعلیم شامل ہیں۔",
    "timeline.2024": "500+ طلباء کا سنگ میل عبور کیا اور 7 قابل اساتذہ کی ٹیم مکمل ہوئی۔",
    // Values
    "value.knowledge.title": "مستند علم",
    "value.knowledge.desc": "قرآن و سنت پر مبنی، ہر سبق مستند اسلامی علم پر قائم ہے۔",
    "value.teaching.title": "شفقت آمیز تعلیم",
    "value.teaching.desc": "ہمارے اساتذہ ہر طالب علم کی صبر، محبت اور انفرادی توجہ سے تربیت کرتے ہیں۔",
    "value.service.title": "خدمت خلق",
    "value.service.desc": "ہم آؤٹ ریچ، تقریبات اور مفت تعلیمی پروگراموں کے ذریعے کمیونٹی کی خدمت کرتے ہیں۔",
    "value.excellence.title": "عمدگی",
    "value.excellence.desc": "ہم اسلامی اور جدید تعلیم دونوں میں اعلیٰ ترین معیار قائم رکھتے ہیں۔",
    // Faculty page
    "faculty.ourteam": "ہماری ٹیم",
    "faculty.experienced": "تجربہ کار اور مخلص",
    "faculty.manager.title": "مینیجنگ ڈائریکٹر",
    "faculty.manager.qual": "دفتری انتظام",
    "faculty.principal.title": "پرنسپل",
    "faculty.principal.qual": "قرآن اور دینیات",
    "faculty.teacher.title": "استاد",
    "faculty.member.manager": "سید جگن حسن اجمالی",
    "faculty.member.tabrez": "حافظ محمد تنویر ذکی",
    "faculty.member.jabir": "حافظ قاری صابر حسین",
    "faculty.member.usman": "حافظ قاری عمران خان",
    "faculty.member.abdullah": "حافظ عبداللہ خان",
    "faculty.member.nizam": "ماسٹر محمد نظام الدین",
    "faculty.member.jamshed": "ماسٹر جمشید خان",
    "faculty.member.pawan": "ماسٹر پرویز احمد",
    "faculty.jabir.qual": "مضامین: اردو، قراءت",
    "faculty.usman.qual": "مضامین: اردو، قراءت",
    "faculty.abdullah.qual": "مضامین: عربی",
    "faculty.nizamuddin.qual": "مضامین: ہندی، ریاضی",
    "faculty.jamshed.qual": "مضامین: ریاضی، جنرل نالج",
    "faculty.pawan.qual": "مضامین: انگریزی، سماجی علوم",
    "home.leadership.badge": "انتظامی ٹیم",
    "home.leadership.heading": "انتظامیہ اور قیادت",
    "home.leadership.subheading": "منیجر اور پرنسپل",
    "home.leadership.viewFaculty": "تمام اساتذہ دیکھیں",
    // Home page labels/news
    "home.news.pinned": "پن کیا گیا",
    "home.news.event": "تقریب",
    "home.news.notice": "اطلاع",
    "home.news.heading": "اعلانات اور خبریں",
    "home.news.subheading": "دارالعلوم جنیدیہ اجمالیہ کی تازہ ترین خبروں سے باخبر رہیں",
    "home.news.admission.title": "2026-27 تعلیمی سال کے لیے نئے داخلے شروع",
    "home.news.admission.desc": "دارالعلوم جنیدیہ اجمالیہ میں حفظ، ناظرہ اور کلاس 1-8 کے لیے درخواستیں قبول کی جا رہی ہیں۔ نشستیں محدود ہیں، جلد درخواست دیں۔",
    "home.news.quran.title": "سالانہ قرآن تلاوت مقابلہ",
    "home.news.quran.desc": "تمام طلباء اور کمیونٹی کے لیے کھلے سالانہ قرآن تلاوت پروگرام میں شامل ہوں۔",
    "home.news.eid.title": "عید تعطیلات کا شیڈول",
    "home.news.eid.desc": "مدرسہ عید کی وجہ سے 18-22 اپریل بند رہے گا۔ کلاسیں 23 اپریل سے شروع ہوں گی۔",
    "home.news.readmore": "مزید پڑھیں",
    "home.news.viewall": "تمام اعلانات دیکھیں",
    // Courses page
    "courses.readytojoin": "اپنا سفر شروع کرنے کے لیے تیار ہیں؟",
    "courses.enrolltext": "آج ہی داخلہ لیں اور جامع اسلامی تعلیم کی طرف پہلا قدم اٹھائیں۔",
    // Contact & Donation
    "contact.sendmessage": "پیغام بھیجیں",
    "contact.getintouch": "رابطہ کریں",
    "contact.location": "مہند، غازی پور",
    "contact.locationdesc": "اتر پردیش",
    "donation.supportus": "ہماری مدد کریں",
    "donation.howtodonate": "عطیہ کیسے دیں",
    "donation.jazakallah": "جزاک اللہ خیر — آپ کا سخاوتی عطیہ ان طلباء کو معیاری تعلیم فراہم کرنے میں مدد کرتا ہے جنہیں اس کی سب سے زیادہ ضرورت ہے۔",
    "donation.scantext": "فوری عطیہ کے لیے UPI ID اسکین یا کاپی کریں",
    "donation.form.name": "نام *",
    "donation.form.phone": "فون نمبر *",
    "donation.form.email": "ای میل (اختیاری)",
    "donation.form.address": "پتہ (اختیاری)",
    "donation.form.whydonate.label": "عطیہ کیوں دیں (اعتماد + وضاحت)",
    "donation.form.whydonate.placeholder": "عطیہ دینے کی وجوہات دیکھیں",
    "donation.form.type.label": "عطیہ کی قسم",
    "donation.form.type.placeholder": "عطیہ کی قسم منتخب کریں",
    "donation.form.submit": "ابھی عطیہ دیں",
    "donation.form.other.placeholder": "براہ کرم اپنے عطیہ کی وجہ بیان کریں...",
    "donation.type.zakat": "زکوٰۃ",
    "donation.type.sadaqah": "صدقہ",
    "donation.type.sponsorship": "طالب علم کی کفالت",
    "donation.type.education": "تعلیمی مدد",
    "donation.type.food": "کھانے کی مدد",
    "donation.type.building": "تعمیراتی فنڈ",
    "donation.type.general": "عمومی عطیہ",
    "donation.type.other": "دیگر",
    "donation.why.1": "غریب طلباء کے لیے مفت تعلیم",
    "donation.why.2": "حفظ قرآن پروگرام",
    "donation.why.3": "کھانے اور رہائش کی مدد",
    "donation.why.4": "کتابیں اور مطالعاتی مواد",
    "donation.popup.title": "جزاک اللہ خیر!",
    "donation.popup.msg1": "اسلامی تعلیم کی حمایت میں آپ کی دلچسپی کا شکریہ۔ واٹس ایپ کھل گیا ہے — ہم سے رابطے کے لیے پیغام بھیجیں۔",
    "donation.popup.msg2": "ہم جلد از جلد آپ سے رابطہ کریں گے۔ صبر فرمائیں — اللہ آپ کو جزائے خیر عطا فرمائے۔ 🤲",
    "donation.popup.btn": "واٹس ایپ پر بھیجیں",
    "donation.popup.close": "یہ ونڈو بند کریں",
    // About gallery
    "about.gallery.title": "فوٹو گیلری",
    "about.gallery.subtitle": "دارالعلوم جنیدیہ اجمالیہ کی زندگی کی ایک جھلک",
    // Footer
    "footer.contactmap": "رابطہ اور نقشہ",
    // Contact enquiry types
    "contact.enquiry.course": "کورس کے بارے میں",
    "contact.enquiry.donation": "عطیہ",
    "contact.enquiry.other": "دیگر",
    // Donation CTA badge
    "donation.cta.badge": "تعاون",
  },

  // ─────────────────────────────────────────────
  // HINDI
  // ─────────────────────────────────────────────
  hi: {
    // Nav
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.courses": "कोर्स",
    "nav.faculty": "शिक्षक",
    "nav.donation": "दान",
    "nav.contact": "संपर्क",
    // Hero
    "hero.welcome": "दारुल उलूम जुनैदिया अजमतिया में आपका स्वागत है",
    "hero.subtitle": "सन् 2004 से गुणवत्तापूर्ण इस्लामी और आधुनिक शिक्षा — महंद, गाजीपुर, उत्तर प्रदेश",
    "hero.slide1.badge": "स्थापना 2004",
    "hero.slide2.badge": "20+ वर्ष",
    "hero.slide3.badge": "500+ छात्र",
    "hero.slide1.desc": "हजारों छात्रों के साथ जुड़ें जिन्होंने कुरान, हदीस और आधुनिक विज्ञान में अपनी नींव मजबूत की। नए शैक्षणिक वर्ष के लिए प्रवेश खुले हैं।",
    "hero.slide2.desc": "हिफ्ज़-उल-कुरान से आधुनिक शिक्षा तक — हमारे संरचित कार्यक्रम हर छात्र की क्षमता को निखारने के लिए बनाए गए हैं।",
    "hero.slide3.desc": "आपका उदार सहयोग ज्ञान के द्वार खुले रखता है। योग्य छात्रों को निःशुल्क और सब्सिडी वाली शिक्षा प्रदान करने में हमारी मदद करें।",
    "hero.apply": "अभी आवेदन करें",
    "hero.donate": "अभी दान करें",
    // About Preview
    "about.preview.title": "हमारे मदरसे के बारे में",
    "about.preview.text": "हम केवल एक शैक्षणिक संस्थान नहीं हैं, बल्कि चरित्र, उद्देश्य और भविष्य के नेतृत्व के निर्माण की मजबूत नींव हैं। हज़रत सैयद अकमल अहमद अजमली (रहमतुल्लाह अलैह) द्वारा स्थापित हमारा मदरसा एक स्पष्ट दृष्टि के साथ शुरू किया गया: ऐसा शिक्षण वातावरण बनाना जहां इस्लामी मूल्य और आधुनिक ज्ञान सामंजस्य के साथ साथ चलें। हमारा मानना है कि सच्ची शिक्षा केवल पुस्तकों तक सीमित नहीं होती, बल्कि सोच, अनुशासन और जिम्मेदारी को आकार देती है। हमारा दृष्टिकोण कुरआनी शिक्षाओं, अकादमिक शिक्षा और व्यक्तिगत विकास को मिलाकर ऐसे व्यक्तियों को तैयार करता है जो आत्मविश्वासी, नैतिक रूप से मजबूत और वास्तविक जीवन की चुनौतियों का सामना करने के लिए तैयार हों। यहाँ हर छात्र को न केवल ज्ञान प्राप्त करने बल्कि ईमानदारी, उद्देश्य और समाज में सकारात्मक योगदान के साथ जीवन जीने की प्रेरणा दी जाती है।दारी का निर्माण करती है। हमारा दृष्टिकोण कुरआनी शिक्षाओं, अकादमिक अध्ययन और व्यक्तित्व विकास को मिलाकर ऐसे व्यक्तियों का निर्माण करता है जो आत्मविश्वासी, नैतिक रूप से मजबूत और वास्तविक जीवन की चुनौतियों का सामना करने के लिए तैयार हों।",
    "about.preview.readmore": "और पढ़ें",
    // Courses
    "courses.title": "हमारे कोर्स",
    "courses.subtitle": "व्यापक इस्लामी और आधुनिक शिक्षा कार्यक्रम",
    "course.hifz.name": "हिफ्ज़-उल-कुरान",
    "course.hifz.desc": "तजवीद के उचित नियमों और उच्चारण के साथ पवित्र कुरान का संपूर्ण याद करना।",
    "course.hifz.duration": "अवधि: 2-3 वर्ष",
    "course.nazra.name": "नाज़रा कुरान",
    "course.nazra.desc": "सही उच्चारण और बुनियादी तजवीद के साथ पवित्र कुरान को प्रवाह के साथ पढ़ना सीखना।",
    "course.nazra.duration": "अवधि: 6-12 महीने",
    "course.alim.name": "कक्षा 1 से 8 (उर्दू और हिंदी माध्यम)",
    "course.alim.desc": "विज्ञान, गणित, अंग्रेज़ी, हिंदी, उर्दू, दीनियात और कुरआन शिक्षा उर्दू और हिंदी माध्यम में स्कूल पाठ्यक्रम के अनुसार पढ़ाई जाती है।",
    "course.alim.duration": "अवधि: 8 वर्ष",
    // Course duration units
    "course.unit.days": "दिन",
    "course.unit.weeks": "सप्ताह",
    "course.unit.months": "महीने",
    "course.unit.years": "वर्ष",
    // Course level labels
    "course.level.beginners": "शुरुआती",
    "course.level.intermediate": "मध्यम",
    "course.level.advanced": "उन्नत",
    "course.level.allages": "सभी आयु",
    // Faculty
    "faculty.title": "हमारे शिक्षक",
    "faculty.subtitle": "अनुभवी और समर्पित शिक्षक",
    "faculty.teacher1.name": "हाफ़िज़ एमडी तनवीर ज़की",
    "faculty.teacher1.title": "प्रधानाचार्य",
    "faculty.teacher1.qual": "कुरान और दीनियात",
    "faculty.teacher2.name": "हाफ़िज़ क़ारी सबिर हुसैन",
    "faculty.teacher2.title": "शिक्षक",
    "faculty.teacher2.qual": "विषय: उर्दू, क़िरात",
    "faculty.teacher3.name": "हाफ़िज़ क़ारी इमरान खान",
    "faculty.teacher3.title": "शिक्षक",
    "faculty.teacher3.qual": "विषय: उर्दू, क़िरात",
    // Donation
    "donation.title": "इस्लामी शिक्षा का समर्थन करें",
    "donation.subtitle": "बेहतर भविष्य के लिए इस्लामी शिक्षा का समर्थन करें",
    "donation.text": "आपका उदार दान उन छात्रों को गुणवत्तापूर्ण इस्लामी और आधुनिक शिक्षा प्रदान करने में मदद करता है जिन्हें इसकी सबसे अधिक आवश्यकता है। हर दान अंतर लाता है।",
    "donation.button": "अभी दान करें",
    "donation.upi": "UPI आईडी",
    "donation.bank": "बैंक विवरण",
    "donation.bank.name": "बैंक का नाम: स्टेट बैंक",
    "donation.bank.account": "खाता: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "आपका योगदान आने वाली पीढ़ियों को शिक्षित करने में मदद करता है।",
    // Footer
    "footer.contact": "संपर्क करें",
    "footer.phone": "फोन: +91 9876543210",
    "footer.email": "ईमेल: darululoomjunaidiaajmalia@gmail.com",
    "footer.address": "महंद, गाजीपुर, उत्तर प्रदेश",
    "footer.quicklinks": "त्वरित लिंक",
    "footer.copyright": "© 2026 दारुल उलूम जुनैदिया अजमतिया। सर्वाधिकार सुरक्षित।",
    "footer.followus": "हमें फॉलो करें",
    "footer.desc": "सीखना, विकास और जिम्मेदारी। मूल्यों और कौशल से व्यक्तियों को सशक्त बनाना। एक बेहतर समाज के लिए मिलकर।",
    // About Page
    "about.title": "दारुल उलूम जुनैदिया अजमतिया के बारे में",
    "about.history.title": "हमारा इतिहास",
    "about.history.text": "मदरसे की स्थापना हज़रत सैयद अकमल अहमद अजमली (रहमतुल्लाह अलैह) ने इस दृष्टि के साथ की थी कि ऐसी संतुलित शिक्षा दी जाए जिसमें इस्लामी शिक्षाएं, आधुनिक ज्ञान और समग्र व्यक्तित्व विकास शामिल हो। इसकी शुरुआत एक छोटे शिक्षण केंद्र के रूप में हुई जहां कुरआनी तालीम के साथ बुनियादी अकादमिक शिक्षा दी जाती थी। निरंतर समर्पण और मजबूत सामुदायिक सहयोग के साथ मदरसे ने धीरे-धीरे अपने कार्यक्रमों का विस्तार किया और हिफ्ज़-उल-कुरआन, नाज़रा तथा संरचित अकादमिक शिक्षा को शामिल किया। आज यह एक सम्मानित संस्थान के रूप में विकसित हो चुका है जो अपने अनुशासित वातावरण, योग्य शिक्षकों और जिम्मेदार नागरिकों के निर्माण के लिए जाना जाता है।",
    "about.mission.title": "हमारा मिशन",
    "about.mission.text": "हमारा मिशन गुणवत्तापूर्ण इस्लामी और आधुनिक शिक्षा प्रदान करना है जो आध्यात्मिक विकास, नैतिक मूल्यों और बौद्धिक उन्नति को पोषित करे। हम कुरान और सुन्नत के ज्ञान से छात्रों को सशक्त बनाना चाहते हैं ताकि वे समाज के जिम्मेदार, नैतिक और उत्पादक सदस्य बन सकें।",
    "about.vision.title": "हमारा विज़न",
    "about.vision.text": "हमारा विज़न एक विशिष्ट इस्लामी शैक्षणिक संस्थान स्थापित करना है जो ज्ञान, चरित्र और सेवा में उत्कृष्टता के लिए पहचाना जाए। हम ऐसी पीढ़ी तैयार करना चाहते हैं जो न केवल इस्लामी मूल्यों को अपनाए बल्कि बदलती वैश्विक समाज व्यवस्था में नेतृत्व, जिम्मेदारी और सकारात्मक योगदान भी दे।",
    "about.founder.title": "संस्थापक का संदेश",
    "about.founder.text": "\"शिक्षा अज्ञानता के अंधकार को दूर करने वाली रोशनी है। दारुल उलूम जुनैदिया अजमतिया में हम हर छात्र के मन के साथ उसके चरित्र और आत्मा का भी विकास करते हैं।\" — हज़रत सैयद अकमल अहमद अजमली रहमतुल्लाह अलैह (सज्जादा नशीन)",
    "about.achievements.title": "हमारी उपलब्धियां",
    "about.achievements.students": "500+ छात्रों को शिक्षित किया",
    "about.achievements.graduates": "200+ हाफ़िज़ स्नातक",
    "about.achievements.years": "20+ वर्षों की सेवा",
    "about.achievements.scholars": "14 कमरे और 3 बड़े हॉल",
    // Contact Page
    "contact.title": "संपर्क करें",
    "contact.subtitle": "हम आपसे सुनना चाहेंगे",
    "contact.form.name": "आपका नाम",
    "contact.form.email": "आपका ईमेल",
    "contact.form.enquiry": "पूछताछ का प्रकार चुनें",
    "contact.form.message": "आपका संदेश",
    "contact.form.submit": "संदेश भेजें",
    "contact.info.title": "संपर्क जानकारी",
    // Hero descriptions
    "hero.about.desc": "1 मार्च 2004 को स्थापित, हम गाजीपुर, उत्तर प्रदेश में इस्लामी मूल्यों और आधुनिक ज्ञान से युवा मनों का पोषण कर रहे हैं।",
    "hero.courses.desc": "हिफ्ज़-उल-कुरान से कक्षा 1-8 हिंदी माध्यम शिक्षा तक — हम इस्लामी और आधुनिक विषयों को मिलाकर एक पूर्ण शिक्षा प्रदान करते हैं।",
    "hero.faculty.desc": "हमारी योग्य शिक्षकों की समर्पित टीम वर्षों के अनुभव और जुनून के साथ अगली पीढ़ी के विद्वानों को आकार दे रही है।",
    "hero.donation.desc": "आपका उदार सहयोग जरूरतमंद छात्रों को मुफ्त शिक्षा, भोजन और आश्रय प्रदान करने में मदद करता है। हर योगदान मायने रखता है।",
    "hero.contact.desc": "कोई प्रश्न है या प्रवेश लेना चाहते हैं? हम यहाँ मदद के लिए हैं। हमसे संपर्क करें और हम जल्द से जल्द जवाब देंगे।",
    // About page extra
    "about.ourstory": "हमारी कहानी",
    "about.milestones": "मुख्य पड़ाव",
    "about.ourjourney": "हमारी यात्रा",
    "about.purpose": "उद्देश्य",
    "about.missionvision": "मिशन स्टेटमेंट",
    "about.whatdrivesus": "हमारी प्रेरणा",
    "about.corevalues": "मुख्य मूल्य",
    "about.wordswisdom": "प्रेरक विचार",
    "about.joincommunity": "हमारे समुदाय से जुड़ें",
    "about.jointext": "हमारी शैक्षिक यात्रा का हिस्सा बनें। आज आवेदन करें या दान देकर हमारे मिशन का समर्थन करें।",
    "about.sendmessage": "संदेश भेजें",
    // Timeline
    "timeline.2004": "दारुल उलूम जुनैदिया अजमतिया की स्थापना 1 मार्च 2004 को हज़रत सैयद अकमल अहमद अजमली रहमतुल्लाह अलैह (सज्जादा नशीन) ने की।",
    "timeline.2006": "पहले बैच ने बुनियादी शिक्षा पूरी की और समुदाय के समर्थन से दाखिले बढ़ते गए।",
    "timeline.2010": "कैम्पस विस्तार में 14 कमरे, 3 बड़े हॉल, एक कार्यालय और एक पुस्तकालय जोड़ा गया।",
    "timeline.2015": "पाठ्यक्रम कक्षा 1 से 8 तक बढ़ाया गया जिसमें विज्ञान, गणित, अंग्रेज़ी, हिंदी, उर्दू, दीनियात और कुरआन शिक्षा शामिल है।",
    "timeline.2024": "संस्थान 500+ छात्रों के मील के पत्थर तक पहुंचा और 7 शिक्षकों की समर्पित टीम तैयार हुई।",
    // Values
    "value.knowledge.title": "प्रामाणिक ज्ञान",
    "value.knowledge.desc": "हर पाठ कुरान और सुन्नत पर आधारित विश्वसनीय इस्लामी ज्ञान पर टिका है।",
    "value.teaching.title": "सहानुभूतिपूर्ण शिक्षण",
    "value.teaching.desc": "हमारे शिक्षक हर छात्र का धैर्य, देखभाल और व्यक्तिगत ध्यान से मार्गदर्शन करते हैं।",
    "value.service.title": "समाज सेवा",
    "value.service.desc": "हम आउटरीच, कार्यक्रमों और सुलभ शिक्षा के माध्यम से समुदाय की सेवा करते हैं।",
    "value.excellence.title": "श्रेष्ठता",
    "value.excellence.desc": "हम इस्लामी और आधुनिक शिक्षा दोनों में उच्च मानक बनाए रखते हैं।",
    // Faculty page
    "faculty.ourteam": "हमारी टीम",
    "faculty.experienced": "समर्पित और अनुभवी",
    "faculty.manager.title": "मैनेजिंग डायरेक्टर",
    "faculty.manager.qual": "कार्यालय प्रबंधन",
    "faculty.principal.title": "प्रधानाचार्य",
    "faculty.principal.qual": "कुरान और दीनियात",
    "faculty.teacher.title": "शिक्षक",
    "faculty.member.manager": "सैयद जगन हसन अजमली",
    "faculty.member.tabrez": "हाफ़िज़ एमडी तनवीर ज़की",
    "faculty.member.jabir": "हाफ़िज़ क़ारी सबिर हुसैन",
    "faculty.member.usman": "हाफ़िज़ क़ारी इमरान खान",
    "faculty.member.abdullah": "हाफ़िज़ अब्दुल्लाह खान",
    "faculty.member.nizam": "मास्टर मोहम्मद निज़ामुद्दीन",
    "faculty.member.jamshed": "मास्टर जमशेद खान",
    "faculty.member.pawan": "मास्टर परवेज़ अहमद",
    "faculty.jabir.qual": "विषय: उर्दू, क़िरात",
    "faculty.usman.qual": "विषय: उर्दू, क़िरात",
    "faculty.abdullah.qual": "विषय: अरबी",
    "faculty.nizamuddin.qual": "विषय: हिंदी, गणित",
    "faculty.jamshed.qual": "विषय: गणित, सामान्य ज्ञान",
    "faculty.pawan.qual": "विषय: अंग्रेज़ी, सामाजिक विज्ञान",
    "home.leadership.badge": "नेतृत्व टीम",
    "home.leadership.heading": "प्रबंधन और नेतृत्व",
    "home.leadership.subheading": "प्रबंधक और प्रधानाचार्य",
    "home.leadership.viewFaculty": "पूरा शिक्षक समूह देखें",
    // Home page labels/news
    "home.news.pinned": "पिन किया गया",
    "home.news.event": "कार्यक्रम",
    "home.news.notice": "सूचना",
    "home.news.heading": "घोषणाएं और समाचार",
    "home.news.subheading": "दारुल उलूम जुनैदिया अजमतिया की ताज़ा जानकारी देखें",
    "home.news.admission.title": "2026-27 शैक्षणिक सत्र के लिए नए प्रवेश शुरू",
    "home.news.admission.desc": "दारुल उलूम जुनैदिया अजमतिया में हिफ्ज़, नाज़रा और कक्षा 1-8 के लिए आवेदन खुले हैं। सीटें सीमित हैं, जल्दी आवेदन करें।",
    "home.news.quran.title": "वार्षिक कुरान तिलावत प्रतियोगिता",
    "home.news.quran.desc": "सभी छात्रों और समुदाय के लिए आयोजित वार्षिक कुरान तिलावत कार्यक्रम में शामिल हों।",
    "home.news.eid.title": "ईद अवकाश समय-सारणी",
    "home.news.eid.desc": "मदरसा 18-22 अप्रैल तक ईद अवकाश के कारण बंद रहेगा। कक्षाएं 23 अप्रैल से शुरू होंगी।",
    "home.news.readmore": "और पढ़ें",
    "home.news.viewall": "सभी घोषणाएं देखें",
    // Courses page
    "courses.readytojoin": "क्या आप अपनी यात्रा शुरू करने के लिए तैयार हैं?",
    "courses.enrolltext": "आज ही प्रवेश लें और व्यापक इस्लामी शिक्षा की ओर पहला कदम बढ़ाएं।",
    // Contact & Donation
    "contact.sendmessage": "संदेश भेजें",
    "contact.getintouch": "संपर्क करें",
    "contact.location": "महंद, गाजीपुर",
    "contact.locationdesc": "उत्तर प्रदेश",
    "donation.supportus": "हमारी सहायता करें",
    "donation.howtodonate": "दान कैसे करें",
    "donation.jazakallah": "जज़ाकल्लाह खैर — आपका उदार दान जरूरतमंद छात्रों को गुणवत्तापूर्ण शिक्षा देने में हमारी मदद करता है।",
    "donation.scantext": "तुरंत दान के लिए UPI आईडी स्कैन या कॉपी करें",
    "donation.form.name": "नाम *",
    "donation.form.phone": "फोन नंबर *",
    "donation.form.email": "ईमेल (वैकल्पिक)",
    "donation.form.address": "पता (वैकल्पिक)",
    "donation.form.whydonate.label": "दान क्यों करें (विश्वास + स्पष्टता)",
    "donation.form.whydonate.placeholder": "दान करने के कारण देखें",
    "donation.form.type.label": "दान का प्रकार",
    "donation.form.type.placeholder": "दान का प्रकार चुनें",
    "donation.form.submit": "अभी दान करें",
    "donation.form.other.placeholder": "कृपया अपने दान का कारण बताएं...",
    "donation.type.zakat": "ज़कात",
    "donation.type.sadaqah": "सदक़ह",
    "donation.type.sponsorship": "छात्र प्रायोजन",
    "donation.type.education": "शिक्षा सहायता",
    "donation.type.food": "भोजन सहायता",
    "donation.type.building": "निर्माण निधि",
    "donation.type.general": "सामान्य दान",
    "donation.type.other": "अन्य",
    "donation.why.1": "वंचित छात्रों के लिए मुफ्त शिक्षा",
    "donation.why.2": "कुरान हिफ्ज़ कार्यक्रम",
    "donation.why.3": "भोजन और आवास सहायता",
    "donation.why.4": "किताबें और अध्ययन सामग्री",
    "donation.popup.title": "जज़ाकल्लाह खैर!",
    "donation.popup.msg1": "इस्लामी शिक्षा का समर्थन करने में आपकी रुचि के लिए धन्यवाद। WhatsApp खुल गया है — हमसे जुड़ने के लिए संदेश भेजें।",
    "donation.popup.msg2": "हम जल्द से जल्द आपसे संपर्क करेंगे। धैर्य रखें — अल्लाह आपको भरपूर पुरस्कार दे। 🤲",
    "donation.popup.btn": "WhatsApp पर भेजें",
    "donation.popup.close": "यह विंडो बंद करें",
    // About gallery
    "about.gallery.title": "फोटो गैलरी",
    "about.gallery.subtitle": "दारुल उलूम जुनैदिया अजमतिया के जीवन की एक झलक",
    // Footer
    "footer.contactmap": "संपर्क और नक्शा",
    // Contact enquiry types
    "contact.enquiry.course": "कोर्स पूछताछ",
    "contact.enquiry.donation": "दान",
    "contact.enquiry.other": "अन्य",
    // Donation CTA badge
    "donation.cta.badge": "सहयोग",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  const dir = lang === "ur" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      <div dir={dir} data-lang={lang}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};